version: '3'

volumes:
  django_sample_db_dev: {}

services:
  nginx:
    build:
      context: .
      dockerfile: ./config/nginx/Dockerfile-dev
    restart : always
    ports:
      - "80:80"
    volumes:
      - .:/app

  db:
    image: postgres
    volumes:
      - django_sample_db_dev:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sampledb
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8

  web:
    build:
      context: .
      dockerfile: ./config/django/Dockerfile-dev
    environment:
      - DJANGO_DEBUG=True
      - DJANGO_DB_HOST=db
      - DJANGO_DB_PORT=5432
      - DJANGO_DB_NAME=sampledb
      - DJANGO_DB_USERNAME=sampleuser
      - DJANGO_DB_PASSWORD=samplesecret
      - DJANGO_SECRET_KEY=dev_secret_key
    expose:
      - "8000"
    command:
      - bash
      - -c
      - |
        python3.6 manage.py makemigrations
        python3.6 manage.py migrate
        gunicorn djangosample.wsgi -b 0.0.0.0:8000 --workers 3
    restart: always

    volumes:
      - ./:/app/
